import React, { useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { AuthShell } from '../components/auth/AuthShell';
import { PasswordInput } from '../components/auth/PasswordInput';
import { FormFeedback } from '../components/auth/FormFeedback';
import { authService, safeInternalPath } from '../auth/authService';
import { normalizeEmail } from '../auth/onboardingValidation';
import { updatePendingRegistrationIdentity } from '../auth/pendingRegistration';
import { useLanguage } from '../context/LanguageContext';
import { onboardingTranslations } from '../i18n/onboardingTranslations';

export function SignInPage() {
  const { language } = useLanguage(); const copy = onboardingTranslations[language]; const navigate = useNavigate(); const location = useLocation(); const destination = safeInternalPath((location.state as { from?: string } | null)?.from, '/account');
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [unverified, setUnverified] = useState(false); const [submitting, setSubmitting] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!navigator.onLine) { setError(copy.common.offline); return; } if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(normalizeEmail(email)) || !password) { setError(copy.validation.email); return; } setSubmitting(true); setError(''); setUnverified(false); try { await authService.signIn(email, password); navigate(destination, { replace: true }); } catch (reason) { const message = reason instanceof Error ? reason.message.toLowerCase() : ''; if (message.includes('email not confirmed')) { setUnverified(true); setError(copy.signIn.unverified); } else setError(language === 'ar' ? 'تعذر تسجيل الدخول بهذه البيانات.' : 'Unable to sign in with those credentials.'); } finally { setSubmitting(false); } };
  const verify = async () => { const normalized = normalizeEmail(email); updatePendingRegistrationIdentity(normalized, destination); try { await authService.resendVerification(normalized, destination); } catch { /* generic destination prevents account disclosure */ } navigate('/verify-email', { state: { email: normalized, from: destination } }); };
  return <AuthShell title={copy.signIn.title} description={copy.signIn.description}><form onSubmit={submit} className="space-y-5" noValidate>{error && <FormFeedback type="error">{error}</FormFeedback>}<div><label htmlFor="email" className="mb-2 block text-sm font-semibold text-slate-200">{copy.signIn.email}</label><input id="email" type="email" dir="ltr" autoComplete="email" value={email} onChange={(event) => setEmail(event.target.value)} className="auth-input" /></div><PasswordInput label={copy.signIn.password} name="password" autoComplete="current-password" value={password} onChange={(event) => setPassword(event.target.value)} showLabel={copy.password.show} hideLabel={copy.password.hide} /><div className="flex justify-end"><Link to="/forgot-password" className="text-sm text-brand-400">{copy.signIn.forgot}</Link></div><button disabled={submitting || !authService.configured()} className="auth-submit">{submitting ? copy.signIn.submitting : copy.signIn.submit}</button>{unverified && <button type="button" onClick={verify} className="min-h-11 w-full rounded-xl border border-brand-500/30 px-4 text-brand-300">{copy.signIn.sendCode}</button>}</form><p className="mt-6 text-center text-sm text-slate-400">{copy.signIn.new} <Link to="/create-account" state={{ from: destination }} className="font-semibold text-brand-400">{copy.signIn.create}</Link></p></AuthShell>;
}
